version: '3'

services:
  node:
    build:
      context: ./node
      args:
        NODE_VERSION: 'latest'
        VUE_CLI_VERSION: ''
        VUE_CLI_SERVICE_GLOBAL_VERSION: ''
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ../app:/app

